#
# Meta
#

- color: e4e669
  description: Already exists
  name: meta:duplicate

- color: e4e669
  description: This doesn't seem right
  name: meta:invalid

- color: e4e669
  description:
  name: meta:needs-review

- color: e4e669
  description:
  name: meta:question

#
# Priority
#

- color: 7819cc
  description: Holy crap this needs get worked on like TODAY
  name: priority:0 - critical

- color: 7819cc
  description: Major inconvenience
  name: priority:1 - high

- color: 7819cc
  description: Can live without it but needs some attention
  name: priority:2 - moderate

- color: 7819cc
  description: Maybe we'll visit this one day
  name: priority:3 - low

#
# Project
#

- color: 009b66
  description:
  name: project:wbm

- color: 009b66
  description:
  name: project:squad-bot

- color: 009b66
  description:
  name: project:stats-site

- color: 009b66
  description:
  name: project:wb-types

- color: 009b66
  description:
  name: project:wbapi

- color: 009b66
  description:
  name: project:wbtimeline

#
# Type
#

- color: d73a4a
  description: Something isn't working as intended
  name: type:bug

- color: 006b75
  description: Problems that require attention
  name: type:report

- color: 006b75
  description: Improvements or addition
  name: type:suggestion

- color: 006b75
  description: Stuff to do
  name: type:task
