[workspace]
members = ["./apps/bbc"]
resolver = "2"

# Enable all optimizations for dependencies, but not for our code
[profile.dev.package."*"]
opt-level = 3

# Enable all optimizations for every code
[profile.release]
opt-level = 3
