name: Deploy Squad Bot Docker Image to Docker Hub

on:
  push:
    paths:
      - apps/squad-bot
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: developomp
          password: ${{ secrets.DEVELOPOMP_DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -f apps/squad-bot/Dockerfile -t developomp/wbp-squad-bot:latest .

      - name: Push Docker Image
        run: docker push developomp/wbp-squad-bot:latest
