name: Deploy WBAPI

on:
    push:
        branches:
            - master
        paths:
            - "apps/wbapi/**"
            - ".github/workflows/deploy-wbapi.yml"
    # allow manual dispatch
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: "pnpm"
                  cache-dependency-path: pnpm-lock.yaml

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-store-

            - name: Install Dependencies
              run: pnpm install

            - name: Build
              working-directory: apps/wbapi
              run: pnpm build

            # FIREBASE_TOKEN retrieved from "firebase login:ci"
            - name: Deploy to Firebase
              working-directory: apps/wbapi
              run: |
                  pnpm install -g firebase-tools
                  pnpm firebase deploy --only functions --project war-brokers-projects --token "${{ secrets.FIREBASE_TOKEN }}"
