# FIREBASE_TOKEN - from "firebase login:ci"
# git diff --quiet: exits with status code 1 if there were differences (https://git-scm.com/docs/git-diff)
name: Main

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy-stats-site:
        required: true
        type: boolean

      deploy-wbapi:
        required: true
        type: boolean

      deploy-wbtimeline:
        required: true
        type: boolean

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      #
      # Prepare
      #

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 30 # get 30 of the most recent commits (default is 1)

      - name: Cache turbo build
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store path
        id: get-pnpm-store-path
        shell: bash
        run: echo "pnpm-store-path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.get-pnpm-store-path.outputs.pnpm-store-path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install Node Dependencies
        run: pnpm install

      - name: Get Playwright's Version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(npx playwright --version | sed 's/Version//')
          echo "Playwright Version: $PLAYWRIGHT_VERSION"
          echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browsers
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      #
      # Stats Site
      #

      - name: Stats Site - Check if changed
        id: changed-stats-site
        continue-on-error: true
        run: git diff --quiet ${{ github.event.before }} ${{ github.event.after }} -- apps/stats-site

      - name: Stats Site - Build
        if: steps.changed-stats-site.outcome == 'failure' || inputs.deploy-stats-site
        run: pnpm build --filter @warbrokers/stats-site

      - name: Stats Site - Lint
        if: steps.changed-stats-site.outcome == 'failure' || inputs.deploy-stats-site
        run: pnpm lint --filter @warbrokers/stats-site

      - name: Stats Site - Unit Tests
        if: steps.changed-stats-site.outcome == 'failure' || inputs.deploy-stats-site
        run: pnpm test:unit --filter @warbrokers/stats-site

      - name: Stats Site - End to End Tests
        if: steps.changed-stats-site.outcome == 'failure' || inputs.deploy-stats-site
        run: pnpm test:e2e --filter @warbrokers/stats-site

      - if: steps.changed-stats-site.outcome == 'failure' || inputs.deploy-stats-site
        run: pnpm dlx firebase-pnpm-workspaces --filter=@warbrokers/stats-site

      - name: Stats Site - Deploy
        if: steps.changed-stats-site.outcome == 'failure' || inputs.deploy-stats-site
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          entryPoint: apps/stats-site
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      #
      # WBAPI
      #

      - name: WBAPI - Check if changed
        id: changed-wbapi
        continue-on-error: true
        run: git diff --quiet ${{ github.event.before }} ${{ github.event.after }} -- apps/wbapi

      - name: WBAPI - Build
        if: steps.changed-wbapi.outcome == 'failure' || inputs.deploy-wbapi
        run: pnpm build --filter @warbrokers/wbapi

      - name: WBAPI - Lint
        if: steps.changed-wbapi.outcome == 'failure' || inputs.deploy-wbapi
        run: pnpm lint --filter @warbrokers/wbapi

      - name: WBAPI - Unit Tests
        if: steps.changed-wbapi.outcome == 'failure' || inputs.deploy-wbapi
        run: pnpm test:unit --filter @warbrokers/wbapi

      - if: steps.changed-wbapi.outcome == 'failure' || inputs.deploy-wbapi
        run: pnpm dlx firebase-pnpm-workspaces --filter=@warbrokers/wbapi

      - name: WBAPI - Deploy
        if: steps.changed-wbapi.outcome == 'failure' || inputs.deploy-wbapi
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          entryPoint: apps/wbapi
          channelId: live

      #
      # WB Timeline
      #

      - name: WB Timeline - Check if changed
        id: changed-wbtimeline
        continue-on-error: true
        run: git diff --quiet ${{ github.event.before }} ${{ github.event.after }} -- apps/wbtimeline

      - name: WB Timeline - Build
        if: steps.changed-wbtimeline.outcome == 'failure' || inputs.deploy-wbtimeline
        run: pnpm build --filter @warbrokers/wbtimeline

      - name: WB Timeline - Lint
        if: steps.changed-wbtimeline.outcome == 'failure' || inputs.deploy-wbtimeline
        run: pnpm lint --filter @warbrokers/wbtimeline

      - name: WB Timeline - Deploy
        if: steps.changed-wbtimeline.outcome == 'failure' || inputs.deploy-wbtimeline
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          entryPoint: apps/wbtimeline
          channelId: live
