name: Sync README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Sync README.md
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.DEVELOPOMP_PAT }}
          CONFIG_PATH: .github/sync-readme.yml
          ASSIGNEES: developomp
          REVIEWERS: developomp
          COMMIT_PREFIX: "chore: "
