name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 30 # get 30 of the most recent commits (default is 1)

      - name: Cache turbo build
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Node Dependencies
        run: pnpm install

      - name: Get Playwright's Version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(npx playwright --version | sed 's/Version//')
          echo "Playwright Version: $PLAYWRIGHT_VERSION"
          echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browsers
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: pnpm playwright install --with-deps

      - name: Build
        env:
          WB_DB_ID: ${{ secrets.WB_DB_ID }}
          WB_DB_PW: ${{ secrets.WB_DB_PW }}
          WB_DB_BASE: ${{ secrets.WB_DB_BASE }}
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Svelte Check
        run: cd apps/stats-site && pnpm svelte-check

      - name: Test (end-to-end)
        env:
          WB_DB_ID: ${{ secrets.WB_DB_ID }}
          WB_DB_PW: ${{ secrets.WB_DB_PW }}
          WB_DB_BASE: ${{ secrets.WB_DB_BASE }}
        run: pnpm test:e2e

      - name: Test (unit)
        env:
          WB_DB_ID: ${{ secrets.WB_DB_ID }}
          WB_DB_PW: ${{ secrets.WB_DB_PW }}
          WB_DB_BASE: ${{ secrets.WB_DB_BASE }}
        run: pnpm test:unit
